#!/bin/bash
echo "Running ktlintFormat..."

./gradlew ktlintFormat

EXIT_CODE=$?

if [ $EXIT_CODE -ne 0 ]; then
  echo "❌ Error: ktlintFormat failed. Please fix the issues and try again."
  exit 1

else
  echo "✅ Formatting successful. Adding changes to the commit"
  git add -u
  exit 0
fi