FROM gradle:8.5.0-jdk21-alpine AS build

ARG GITHUB_ACTOR
ARG REDIS_TOKEN

ENV GITHUB_ACTOR=${GITHUB_ACTOR}
ENV REDIS_TOKEN=${REDIS_TOKEN}

COPY . /home/gradle/src
WORKDIR /home/gradle/src

RUN gradle :api:bootJar --no-daemon \
    -Pgpr.user=${GITHUB_ACTOR} \
    -Pgpr.key=${REDIS_TOKEN}

FROM eclipse-temurin:21-jre-alpine
EXPOSE 8080

RUN mkdir -p /app/newrelic
COPY --from=build /home/gradle/src/newrelic/newrelic.jar /app/newrelic/
COPY --from=build /home/gradle/src/newrelic/newrelic.yml /app/newrelic/

COPY --from=build /home/gradle/src/api/build/libs/*.jar /app/spring-boot-application.jar

ENTRYPOINT ["java", "-javaagent:/app/newrelic/newrelic.jar", -Dnewrelic.config.license_key=${NEW_RELIC_LICENSE_KEY}, "-jar", "/app/spring-boot-application.jar"]