FROM gradle:8.5.0-jdk21-alpine AS build
COPY . /home/gradle/src
WORKDIR /home/gradle/src
RUN gradle :api:bootJar --no-daemon

FROM eclipse-temurin:21-jre-alpine
EXPOSE 8080

ENV SPRING_PROFILES_ACTIVE=production
ENV JAVA_OPTS=""

RUN mkdir /app
COPY --from=build /home/gradle/src/api/build/libs/*.jar /app/spring-boot-application.jar

ENTRYPOINT sh -c "java ${JAVA_OPTS} -jar -Dspring.profiles.active=${SPRING_PROFILES_ACTIVE} /app/spring-boot-application.jar"