FROM gradle:8.5.0-jdk21-alpine

# Accept build arguments for GitHub credentials
ARG GITHUB_ACTOR
ARG REDIS_TOKEN

# Set environment variables for Gradle
ENV GITHUB_ACTOR=${GITHUB_ACTOR}
ENV REDIS_TOKEN=${REDIS_TOKEN}

COPY . /home/gradle/src
WORKDIR /home/gradle/src
RUN gradle build --no-daemon
EXPOSE 8080
ENTRYPOINT ["java","-jar", "/home/gradle/src/build/libs/Snippet-Service-1.1.2.jar"]