services:
  api:
    container_name: "snippet-service-api"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_ACTOR: ${GITHUB_ACTOR}
        REDIS_TOKEN: ${REDIS_TOKEN}
    image: ghcr.io/tef-austral/snippet-api:latest
    ports:
      - "8002:8080"
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: snippet_db
    image: postgres:16
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER_SNIPPET}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_SNIPPET}
      POSTGRES_DB: ${POSTGRES_DB_SNIPPET}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: