plugins {
    id 'buildlogic.kotlin-common-conventions'
    id 'org.jetbrains.kotlin.jvm'
}



repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.jetbrains.kotlin:kotlin-test'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
    implementation project(':commoncontracts')
}

test {
    useJUnitPlatform()
}
kotlin {
    jvmToolchain(21)
}