spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${POSTGRES_DB_SNIPPET}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER_SNIPPET}
    password: ${POSTGRES_PASSWORD_SNIPPET}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  redis:
    stream:
      snippet:
        key: snippet-events

  asset:
    service:
      url: ${ASSET_SERVICE_URL}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH0_ISSUER_URI}

      client:
        registration:
          auth0-m2m:
            client-id: ${SNIPPET_SERVICE_M2M_CLIENT_ID}
            client-secret: ${SNIPPET_SERVICE_M2M_CLIENT_SECRET}
            authorization-grant-type: client_credentials
            scope: ${AUTH0_M2M_SCOPE:}
        provider:
          auth0-m2m:
            token-uri: ${AUTH0_ISSUER_URI}oauth/token

authorization:
  service:
    url: ${AUTHORIZATION_SERVICE_URL}

printscript:
  service:
    url: ${PRINTSCRIPT_SERVICE_URL:http://printscript-service-api:8080}

auth0:
  audience: ${AUTH0_AUDIENCE}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always