plugins {
    id 'buildlogic.kotlin-common-conventions'
    id 'org.jetbrains.kotlin.jvm'
}

group = 'com.github.tef-austral.snippet-service'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.jetbrains.kotlin:kotlin-test'
    implementation project(':commondto')
}

test {
    useJUnitPlatform()
}
kotlin {
    jvmToolchain(21)
}