plugins {
    id 'buildlogic.kotlin-common-conventions'
}

group = 'com.github.tef-austral.snippet-service'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.jetbrains.kotlin:kotlin-test'
    testImplementation 'org.jetbrains.kotlinx:kotlinx-coroutines-test:1.7.3'
    testImplementation 'org.mockito.kotlin:mockito-kotlin:5.1.0'
    testImplementation 'org.mockito:mockito-inline:5.2.0'
    implementation("org.springframework.boot:spring-boot-starter-data-redis")
    testImplementation("io.mockk:mockk:1.13.10")
    implementation 'org.springframework.boot:spring-boot-starter-websocket'
    implementation("org.springframework:spring-messaging")
    implementation project(':commondto')
    implementation project(':commondata')
    implementation project(':commoncontracts')
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2"
    implementation('org.austral.ingsis:redis-streams-mvc:0.1.13')
}

test {
    useJUnitPlatform()
}
kotlin {
    jvmToolchain(21)
}